"""Avenues / rues Kinshasa (OpenStreetMap).

- KINSHASA_CITY_AVENUES : ways name~Avenue dans Kinshasa (fallback).
- KINSHASA_AVENUES_BY_COMMUNE : extracts par polygone commune quand disponibles.
- avenues_for_commune(name) : extract commune ou fallback city.
"""

from __future__ import annotations

KINSHASA_CITY_AVENUES: list[tuple[str, str]] = [
    ('AVENUE', '. Anuarite'),
    ('AVENUE', '2 Moanda'),
    ('AVENUE', '24 Novembre'),
    ('AVENUE', '4 Avril'),
    ('AVENUE', '4 Janvier'),
    ('AVENUE', '8 DÃ©cembre'),
    ('AVENUE', 'Abattoire'),
    ('AVENUE', 'Abedy'),
    ('AVENUE', 'Abibo'),
    ('AVENUE', 'Abindi'),
    ('AVENUE', 'ACP'),
    ('AVENUE', 'Akenge'),
    ('AVENUE', 'Akula'),
    ('AVENUE', 'Akula 1'),
    ('AVENUE', 'Alex Musa'),
    ('AVENUE', 'Allemagne'),
    ('AVENUE', 'Amani 10'),
    ('AVENUE', 'Amisi'),
    ('AVENUE', 'Angenga'),
    ('AVENUE', 'Anunga'),
    ('AVENUE', 'Arc Bleu'),
    ('AVENUE', 'Arpenteur'),
    ('AVENUE', 'Aru'),
    ('AVENUE', 'Assoba'),
    ('AVENUE', 'Assolongo'),
    ('AVENUE', 'Assossa'),
    ('AVENUE', 'Avenue, Du Parc II'),
    ('AVENUE', 'Avenue, FrontiÃ¨re'),
    ('AVENUE', 'Avenue, Lilas'),
    ('AVENUE', 'Avenue1 Moanda'),
    ('AVENUE', 'AvenueBateke'),
    ('AVENUE', 'AvenueLokolama'),
    ('AVENUE', 'Baboma'),
    ('AVENUE', 'Badjoko'),
    ('AVENUE', 'Bado'),
    ('AVENUE', 'Bahumbu'),
    ('AVENUE', 'Bakali'),
    ('AVENUE', 'Baketukila'),
    ('AVENUE', 'Bakole'),
    ('AVENUE', 'Bakusu'),
    ('AVENUE', 'Balombadio'),
    ('AVENUE', 'Balonzi'),
    ('AVENUE', 'Bambala'),
    ('AVENUE', 'bambelota'),
    ('AVENUE', 'Bamboma'),
    ('AVENUE', 'Bampela'),
    ('AVENUE', 'Bananier'),
    ('AVENUE', 'Banda'),
    ('AVENUE', 'Bandoma'),
    ('AVENUE', 'Bandulugu'),
    ('AVENUE', 'Bandundu'),
    ('AVENUE', 'Bangala'),
    ('AVENUE', 'Banku'),
    ('AVENUE', 'Bantandu'),
    ('AVENUE', 'Banunu'),
    ('AVENUE', 'Banunu 2'),
    ('AVENUE', 'Banyango'),
    ('AVENUE', 'Baruti'),
    ('AVENUE', 'Bas Fleuve'),
    ('AVENUE', 'Bas-Congo'),
    ('AVENUE', 'Basalapasu'),
    ('AVENUE', 'Bashala'),
    ('AVENUE', 'Basoko'),
    ('AVENUE', 'Basuku'),
    ('AVENUE', 'Bateke'),
    ('AVENUE', 'Batshikama'),
    ('AVENUE', 'Baudouin'),
    ('AVENUE', 'Bayaka'),
    ('AVENUE', 'Bayindu'),
    ('AVENUE', 'Bazoko'),
    ('AVENUE', 'Beaux-Arts'),
    ('AVENUE', 'Beka'),
    ('AVENUE', 'Belebinda'),
    ('AVENUE', 'Benamukuele'),
    ('AVENUE', 'Beni'),
    ('AVENUE', 'Benia'),
    ('AVENUE', 'Benkana'),
    ('AVENUE', 'Benseke'),
    ('AVENUE', 'Betambe'),
    ('AVENUE', 'Betene'),
    ('AVENUE', 'Beyapumbu'),
    ('AVENUE', 'Bibito'),
    ('AVENUE', 'Bibwa'),
    ('AVENUE', 'Bidungi'),
    ('AVENUE', 'Bie'),
    ('AVENUE', 'Biey'),
    ('AVENUE', 'Bikela'),
    ('AVENUE', 'Biko'),
    ('AVENUE', 'Bilonda'),
    ('AVENUE', 'Bindungi'),
    ('AVENUE', 'Birmanie'),
    ('AVENUE', 'Bitshakutshaku'),
    ('AVENUE', 'Bizuba'),
    ('AVENUE', 'Bobila Dawa'),
    ('AVENUE', 'Bobobliko'),
    ('AVENUE', 'Boboliko'),
    ('AVENUE', 'Bobondo'),
    ('AVENUE', 'Bobongo'),
    ('AVENUE', 'Bobozo'),
    ('AVENUE', 'Boende'),
    ('AVENUE', 'Bohozo'),
    ('AVENUE', 'Bokele'),
    ('AVENUE', 'Bokiba'),
    ('AVENUE', 'Boko'),
    ('AVENUE', 'Bokoma'),
    ('AVENUE', 'Bokuka'),
    ('AVENUE', 'Bolene'),
    ('AVENUE', 'Bolenge'),
    ('AVENUE', 'Bolingo'),
    ('AVENUE', 'Bolobo'),
    ('AVENUE', 'Bolongo'),
    ('AVENUE', 'Bomboyo'),
    ('AVENUE', 'Bomongo'),
    ('AVENUE', 'Bompete'),
    ('AVENUE', 'Bon Coin'),
    ('AVENUE', 'Bondjobo'),
    ('AVENUE', 'Bonga'),
    ('AVENUE', 'Bongambo'),
    ('AVENUE', 'Bongi'),
    ('AVENUE', 'Bongolo'),
    ('AVENUE', 'Bosango'),
    ('AVENUE', 'Bosekota'),
    ('AVENUE', 'Bosembo'),
    ('AVENUE', 'Boyata'),
    ('AVENUE', 'Boyau'),
    ('AVENUE', 'Brabanta'),
    ('AVENUE', 'Brasserie'),
    ('AVENUE', 'Brikin'),
    ('AVENUE', 'Buadi'),
    ('AVENUE', 'Buala'),
    ('AVENUE', 'Budjala'),
    ('AVENUE', 'Buffle'),
    ('AVENUE', 'buka'),
    ('AVENUE', 'Bukala'),
    ('AVENUE', 'Bukanga'),
    ('AVENUE', 'Bula'),
    ('AVENUE', 'Bulambemba'),
    ('AVENUE', 'Bulungu'),
    ('AVENUE', 'Bumba'),
    ('AVENUE', 'Bumba 2'),
    ('AVENUE', 'Bumba 3'),
    ('AVENUE', 'Bungudi'),
    ('AVENUE', 'Busu-Djanoa'),
    ('AVENUE', 'Butulu'),
    ('AVENUE', 'Buzi'),
    ('AVENUE', 'By Pass'),
    ('AVENUE', "Caisse d'Epargne"),
    ('AVENUE', 'Carisse Sesebe'),
    ('AVENUE', 'Cataractes'),
    ('AVENUE', 'Ceinture Verte'),
    ('AVENUE', 'Chef Kinzonzi'),
    ('AVENUE', 'ChrÃ©tienne'),
    ('AVENUE', 'Chute de Lofoy'),
    ('AVENUE', 'Claude Maluma'),
    ('AVENUE', 'Cogelos'),
    ('AVENUE', 'CollÃ¨ge'),
    ('AVENUE', 'Colonel Ebeya'),
    ('AVENUE', 'Colonel Ipolo'),
    ('AVENUE', 'Colonel Kaya'),
    ('AVENUE', 'Colonel Lukusa'),
    ('AVENUE', 'Colonel Mondjiba'),
    ('AVENUE', 'Colonel Mpia'),
    ('AVENUE', 'Colonel Yav'),
    ('AVENUE', 'Commando'),
    ('AVENUE', 'Commercial'),
    ('AVENUE', 'CPA'),
    ('AVENUE', "d'Inkisi"),
    ('AVENUE', "d'Isiro"),
    ('AVENUE', "d'Udjidji"),
    ('AVENUE', 'Dahlias'),
    ('AVENUE', 'Daudet Luboya'),
    ('AVENUE', 'de Bangala'),
    ('AVENUE', 'de Cocotier'),
    ('AVENUE', 'de Goma'),
    ('AVENUE', 'de Kabolo'),
    ('AVENUE', 'de Kalemie'),
    ('AVENUE', 'de Kananga'),
    ('AVENUE', 'de Kapanga'),
    ('AVENUE', 'de Kasongo'),
    ('AVENUE', 'de Kato'),
    ('AVENUE', 'de Kikwit'),
    ('AVENUE', 'de Kilosa'),
    ('AVENUE', 'de Kongolo'),
    ('AVENUE', "de l'Avenir"),
    ('AVENUE', "de l'Ecole"),
    ('AVENUE', "de l'Eglise Primitive"),
    ('AVENUE', "de l'Eglise Saint Thomas"),
    ('AVENUE', "de l'Escorte PrÃ©sidentielle"),
    ('AVENUE', "de l'Est"),
    ('AVENUE', "de l'Hopital"),
    ('AVENUE', "de l'IndÃ©pendence"),
    ('AVENUE', "de l'INSS"),
    ('AVENUE', "de l'OMS"),
    ('AVENUE', "de l'Ouest"),
    ('AVENUE', "de l'Ubangi"),
    ('AVENUE', "de l'UniversitÃ©"),
    ('AVENUE', "de l'Usine"),
    ('AVENUE', "de l'Ã\x89cole"),
    ('AVENUE', "de l'Ã\x89glise"),
    ('AVENUE', "de l'Ã\x89quateur"),
    ('AVENUE', "de l'Ã\x89tat-Major"),
    ('AVENUE', "de l'Ã©cole"),
    ('AVENUE', "De l'Ã©curie"),
    ('AVENUE', "de l'Ã©glise"),
    ('AVENUE', 'De l`hopital'),
    ('AVENUE', 'de la Chapelle'),
    ('AVENUE', 'de la Commune'),
    ('AVENUE', 'de la Corniche'),
    ('AVENUE', 'de la Crique'),
    ('AVENUE', 'de la Croix Rouge'),
    ('AVENUE', 'de la Douane'),
    ('AVENUE', 'de la Ferme'),
    ('AVENUE', 'de la Fondation'),
    ('AVENUE', 'de la Force Publique'),
    ('AVENUE', 'de la Funa'),
    ('AVENUE', 'de la Gombe'),
    ('AVENUE', 'de la IIÃ¨me RÃ©publique'),
    ('AVENUE', 'de la Justice'),
    ('AVENUE', 'de la LibÃ©ration'),
    ('AVENUE', 'de la Lowa'),
    ('AVENUE', 'de la Mission'),
    ('AVENUE', 'de la Mongala'),
    ('AVENUE', 'de la Montagne'),
    ('AVENUE', 'de la NÃ©cropole'),
    ('AVENUE', 'de la Paix'),
    ('AVENUE', 'de la Paix 2'),
    ('AVENUE', 'de la Permanence'),
    ('AVENUE', 'de la Pharmacie'),
    ('AVENUE', 'de la Plaine'),
    ('AVENUE', 'de la Presse'),
    ('AVENUE', 'de la Prison'),
    ('AVENUE', 'de la Riviere'),
    ('AVENUE', 'de la RÃ©gion'),
    ('AVENUE', 'de la RÃ©publique'),
    ('AVENUE', 'de la SantÃ©'),
    ('AVENUE', 'de la Science'),
    ('AVENUE', 'de la SNEL'),
    ('AVENUE', 'de la Source'),
    ('AVENUE', 'de la T.S.F.'),
    ('AVENUE', 'de la Tshuapa'),
    ('AVENUE', 'de la VallÃ©e'),
    ('AVENUE', 'de la Victoire'),
    ('AVENUE', 'de Lokalama'),
    ('AVENUE', 'de lâ\x80\x99AÃ©rodrome'),
    ('AVENUE', 'de lâ\x80\x99HÃ´pital'),
    ('AVENUE', 'de lâ\x80\x99OUA'),
    ('AVENUE', 'de lâ\x80\x99Ouganda'),
    ('AVENUE', 'de lâ\x80\x99UniversitÃ©'),
    ('AVENUE', 'de lâ\x80\x99Ã\x89cole'),
    ('AVENUE', 'de Madimba'),
    ('AVENUE', 'de Mushie'),
    ('AVENUE', 'de Rutshuru'),
    ('AVENUE', 'de Tabora'),
    ('AVENUE', 'de Vivi'),
    ('AVENUE', 'de Zomfi'),
    ('AVENUE', 'Dekese'),
    ('AVENUE', 'des 18 Parcelles'),
    ('AVENUE', 'des ambassadeur'),
    ('AVENUE', 'des Ambassadeurs'),
    ('AVENUE', 'des AmÃ©ricains'),
    ('AVENUE', 'des Anciens Combattants'),
    ('AVENUE', 'des Aviateurs'),
    ('AVENUE', 'des Batetela'),
    ('AVENUE', 'des CarriÃ¨res'),
    ('AVENUE', 'des Cataractes'),
    ('AVENUE', 'des Choux'),
    ('AVENUE', 'des Citroniers'),
    ('AVENUE', 'des Citronniers'),
    ('AVENUE', 'des Cliniques'),
    ('AVENUE', 'des Coteaux'),
    ('AVENUE', 'des Coyaviers'),
    ('AVENUE', 'des Ecuries'),
    ('AVENUE', 'des Eglises'),
    ('AVENUE', 'des Entrepots'),
    ('AVENUE', 'des Flamboyants'),
    ('AVENUE', 'des Forces ArmÃ©es'),
    ('AVENUE', 'des FrÃ¨res / Rue Kikwit'),
    ('AVENUE', 'des GÃ©nÃ©raux'),
    ('AVENUE', 'des Huileries'),
    ('AVENUE', 'des IngÃ©nieurs'),
    ('AVENUE', 'des Jacarandas'),
    ('AVENUE', 'des Monts Virunga'),
    ('AVENUE', 'des Nations Unies'),
    ('AVENUE', 'des Officiers'),
    ('AVENUE', 'des Oliviers'),
    ('AVENUE', 'des Orangers'),
    ('AVENUE', 'des OrchidÃ©es'),
    ('AVENUE', 'des Palmiers'),
    ('AVENUE', 'des Pommiers'),
    ('AVENUE', 'des Pruniers'),
    ('AVENUE', 'des Sports'),
    ('AVENUE', 'des SÃ©nÃ©galais'),
    ('AVENUE', 'des Tomates'),
    ('AVENUE', 'des Vieillards'),
    ('AVENUE', 'des Ã\x89tangs'),
    ('AVENUE', 'des Ã\x89toiles'),
    ('AVENUE', 'Destinateur'),
    ('AVENUE', 'Deux Maisons'),
    ('AVENUE', 'Dialele'),
    ('AVENUE', 'Diangienda'),
    ('AVENUE', 'Diasuka'),
    ('AVENUE', 'Dimbelenge'),
    ('AVENUE', 'Dimuka'),
    ('AVENUE', 'Dinganga'),
    ('AVENUE', 'Diomi'),
    ('AVENUE', 'Disengomoka'),
    ('AVENUE', 'Division'),
    ('AVENUE', 'Diwaz'),
    ('AVENUE', 'Dodoma'),
    ('AVENUE', 'Dongo'),
    ('AVENUE', 'Dracena'),
    ('AVENUE', 'du 1er Juillet'),
    ('AVENUE', 'du 30 juin'),
    ('AVENUE', 'du Baketukila'),
    ('AVENUE', 'du Bandundu'),
    ('AVENUE', 'du Bas-Congo'),
    ('AVENUE', 'du Bocage'),
    ('AVENUE', 'du Camp'),
    ('AVENUE', 'du Canal'),
    ('AVENUE', 'du Centre'),
    ('AVENUE', 'du Cercle'),
    ('AVENUE', 'du CimetiÃ¨re'),
    ('AVENUE', 'du Cocotier'),
    ('AVENUE', 'du colonel Tshatshi'),
    ('AVENUE', 'du Combattant'),
    ('AVENUE', 'du ComitÃ© urbain'),
    ('AVENUE', 'du Commerce'),
    ('AVENUE', 'du Congo'),
    ('AVENUE', 'du Fleuve'),
    ('AVENUE', 'du Grand SÃ©minaire'),
    ('AVENUE', 'du Haut Commandement'),
    ('AVENUE', 'du Haut-Congo'),
    ('AVENUE', 'du Haut-Congo 1'),
    ('AVENUE', 'du KasaÃ¯'),
    ('AVENUE', 'du Kwilu'),
    ('AVENUE', 'du Lac'),
    ('AVENUE', 'du Livre'),
    ('AVENUE', 'du Lokoro'),
    ('AVENUE', 'du Marais'),
    ('AVENUE', 'du Marche'),
    ('AVENUE', 'du MarchÃ©'),
    ('AVENUE', 'du Mont des Arts'),
    ('AVENUE', 'du Parc'),
    ('AVENUE', 'du Parti'),
    ('AVENUE', 'du Pasteur Lungi Lukumbi'),
    ('AVENUE', 'du Petit pont'),
    ('AVENUE', 'du Plateau'),
    ('AVENUE', 'du Pont'),
    ('AVENUE', 'du Port'),
    ('AVENUE', 'du ProgrÃ¨s'),
    ('AVENUE', 'du Roi Baudoin'),
    ('AVENUE', 'du Roi Baudouin'),
    ('AVENUE', 'du Sankuru'),
    ('AVENUE', 'du Stade'),
    ('AVENUE', 'du Sud'),
    ('AVENUE', 'du Syndicat'),
    ('AVENUE', 'du Tchad'),
    ('AVENUE', 'du Temple'),
    ('AVENUE', 'du Tourisme'),
    ('AVENUE', 'du Village'),
    ('AVENUE', 'Duma'),
    ('AVENUE', 'Dumi'),
    ('AVENUE', 'Ebonda'),
    ('AVENUE', 'Ecole'),
    ('AVENUE', 'Ekumba'),
    ('AVENUE', 'Elengesa'),
    ('AVENUE', 'Esengo'),
    ('AVENUE', 'Essabe'),
    ('AVENUE', 'Eteni'),
    ('AVENUE', 'Etoile'),
    ('AVENUE', 'Etonga'),
    ('AVENUE', 'Ezo'),
    ('AVENUE', 'Fabiesa'),
    ('AVENUE', 'FAO'),
    ('AVENUE', 'Faradje'),
    ('AVENUE', 'Fatundu'),
    ('AVENUE', 'Fayala'),
    ('AVENUE', 'Fesa'),
    ('AVENUE', 'Feshi'),
    ('AVENUE', 'Fiadaka'),
    ('AVENUE', 'fichÃ©'),
    ('AVENUE', 'Fidami'),
    ('AVENUE', 'Fikisi'),
    ('AVENUE', 'Fina Congo'),
    ('AVENUE', 'Finant'),
    ('AVENUE', 'Flambeau'),
    ('AVENUE', 'Forgerons'),
    ('AVENUE', 'ForÃªt'),
    ('AVENUE', 'FrontiÃ¨re'),
    ('AVENUE', 'FrÃ©dÃ©ric'),
    ('AVENUE', 'Fumu Panzu'),
    ('AVENUE', 'Gambela'),
    ('AVENUE', 'GardÃ©nias'),
    ('AVENUE', 'Garneaux'),
    ('AVENUE', 'Gbadolite'),
    ('AVENUE', 'Gemena'),
    ('AVENUE', 'General Babia'),
    ('AVENUE', 'General Bosango'),
    ('AVENUE', 'Gindu'),
    ('AVENUE', 'Gizhenga'),
    ('AVENUE', 'Goa'),
    ('AVENUE', 'Godetias'),
    ('AVENUE', 'Goma'),
    ('AVENUE', 'Gombe'),
    ('AVENUE', 'Gombe Sud'),
    ('AVENUE', 'Gombe-Matadi'),
    ('AVENUE', 'Gombeside'),
    ('AVENUE', 'Gombo'),
    ('AVENUE', 'Good year'),
    ('AVENUE', 'Goodyear'),
    ('AVENUE', 'Grand Seminaire'),
    ('AVENUE', 'Gungu'),
    ('AVENUE', 'GÃ©camines'),
    ('AVENUE', 'GÃ©nÃ©ral Bakatamba'),
    ('AVENUE', 'GÃ©nÃ©ral Basuki'),
    ('AVENUE', 'GÃ©nÃ©ral Bosango'),
    ('AVENUE', 'GÃ©nÃ©ral Itambo'),
    ('AVENUE', 'GÃ©nÃ©ral Moke'),
    ('AVENUE', 'GÃ©nÃ©ral Mulamba'),
    ('AVENUE', 'Haut-Congo 2'),
    ('AVENUE', 'haute tension'),
    ('AVENUE', 'Henri Bongolo'),
    ('AVENUE', 'Hesbaye'),
    ('AVENUE', 'Idiamine'),
    ('AVENUE', 'Idiofa'),
    ('AVENUE', 'Ilunga'),
    ('AVENUE', 'Inga'),
    ('AVENUE', 'Ingende'),
    ('AVENUE', 'Ingila'),
    ('AVENUE', 'Inkisi'),
    ('AVENUE', 'Inzia'),
    ('AVENUE', 'Ipenge'),
    ('AVENUE', 'Isangi'),
    ('AVENUE', 'Isangi 1'),
    ('AVENUE', 'Isangi 2'),
    ('AVENUE', 'Itaga'),
    ('AVENUE', 'Itali Lota'),
    ('AVENUE', 'Itimbiri'),
    ('AVENUE', 'Iveco'),
    ('AVENUE', 'Ixhoras Avenue'),
    ('AVENUE', 'Jeunesse'),
    ('AVENUE', 'Jireh'),
    ('AVENUE', 'Joli-Parc'),
    ('AVENUE', 'Kabalo'),
    ('AVENUE', 'Kabambare'),
    ('AVENUE', 'Kabasele'),
    ('AVENUE', 'Kabasele Tshiamala Joseph'),
    ('AVENUE', 'Kabinda'),
    ('AVENUE', 'Kabyle'),
    ('AVENUE', 'Kadiya'),
    ('AVENUE', 'Kahemba'),
    ('AVENUE', 'Kahungu'),
    ('AVENUE', 'Kainda'),
    ('AVENUE', 'Kajiba'),
    ('AVENUE', 'Kalaka'),
    ('AVENUE', 'Kalala Nzau'),
    ('AVENUE', 'Kalelu'),
    ('AVENUE', 'Kalembelembe'),
    ('AVENUE', 'Kalongo'),
    ('AVENUE', 'Kalume'),
    ('AVENUE', 'Kalume Mwana Kahambwa'),
    ('AVENUE', 'Kam Kam'),
    ('AVENUE', 'Kama'),
    ('AVENUE', 'Kamak 2'),
    ('AVENUE', 'Kamaniola'),
    ('AVENUE', 'Kamanyola'),
    ('AVENUE', 'Kamba'),
    ('AVENUE', 'kamina'),
    ('AVENUE', 'Kananga'),
    ('AVENUE', 'Kandola'),
    ('AVENUE', 'Kandolo'),
    ('AVENUE', 'Kanga'),
    ('AVENUE', 'Kanianga'),
    ('AVENUE', 'Kanioka'),
    ('AVENUE', 'Kansanzi'),
    ('AVENUE', 'Kanza'),
    ('AVENUE', 'Kapanga'),
    ('AVENUE', 'Kapela'),
    ('AVENUE', 'Kapenda'),
    ('AVENUE', 'Kasa Vubu'),
    ('AVENUE', 'Kasa-Vubu'),
    ('AVENUE', 'Kasai'),
    ('AVENUE', 'Kasangulu'),
    ('AVENUE', 'Kasanzi'),
    ('AVENUE', 'KasaÃ¯'),
    ('AVENUE', 'Kase Vubu'),
    ('AVENUE', 'Kasereka'),
    ('AVENUE', 'Kasilu'),
    ('AVENUE', 'Kasongo'),
    ('AVENUE', 'Kasongo Lunda'),
    ('AVENUE', 'Kasongo Sangolo'),
    ('AVENUE', 'kasuku'),
    ('AVENUE', 'Katakokombe'),
    ('AVENUE', 'Katakokombe II'),
    ('AVENUE', 'Katanga'),
    ('AVENUE', 'Kato'),
    ('AVENUE', 'Kauka'),
    ('AVENUE', 'Kayamesu'),
    ('AVENUE', 'Kayinda'),
    ('AVENUE', 'kazadi'),
    ('AVENUE', 'Kemba'),
    ('AVENUE', 'Kembe'),
    ('AVENUE', 'Kembo'),
    ('AVENUE', 'Kemi'),
    ('AVENUE', 'Kenge'),
    ('AVENUE', 'Kiaku'),
    ('AVENUE', 'Kiampewa'),
    ('AVENUE', 'Kianza'),
    ('AVENUE', 'Kibamba'),
    ('AVENUE', 'Kibanda'),
    ('AVENUE', 'Kibentele'),
    ('AVENUE', 'Kibunbo 1'),
    ('AVENUE', 'Kibunbo 2'),
    ('AVENUE', 'Kibunda'),
    ('AVENUE', 'Kidima'),
    ('AVENUE', 'Kiese'),
    ('AVENUE', 'Kifunga'),
    ('AVENUE', 'Kigoma'),
    ('AVENUE', 'Kika'),
    ('AVENUE', 'Kikama II'),
    ('AVENUE', 'kikembi'),
    ('AVENUE', 'Kikweta'),
    ('AVENUE', 'Kikwit'),
    ('AVENUE', 'Kikwit 2'),
    ('AVENUE', 'Kilele'),
    ('AVENUE', 'Kilembo'),
    ('AVENUE', 'Kilo-Moto'),
    ('AVENUE', 'Kilolo Musamba Lubemba'),
    ('AVENUE', 'Kilombwe'),
    ('AVENUE', 'Kilueso'),
    ('AVENUE', 'Kiluinzi'),
    ('AVENUE', 'Kilumbu'),
    ('AVENUE', 'Kimangunu'),
    ('AVENUE', 'Kimani'),
    ('AVENUE', 'Kimbangu'),
    ('AVENUE', 'Kimbao'),
    ('AVENUE', 'Kimbata'),
    ('AVENUE', 'Kimbenza'),
    ('AVENUE', 'Kimbondo'),
    ('AVENUE', 'Kimbongo'),
    ('AVENUE', 'Kimbwala'),
    ('AVENUE', 'Kiminzita'),
    ('AVENUE', 'Kimondo'),
    ('AVENUE', 'Kimpaka'),
    ('AVENUE', 'Kimpakasa'),
    ('AVENUE', 'Kimpese'),
    ('AVENUE', 'Kimpika'),
    ('AVENUE', 'Kimpika 2'),
    ('AVENUE', 'Kimpoko'),
    ('AVENUE', 'Kimpunza'),
    ('AVENUE', 'Kimpwanza'),
    ('AVENUE', 'kimuisi'),
    ('AVENUE', 'Kimvuka'),
    ('AVENUE', 'Kimvula'),
    ('AVENUE', 'Kimwenza'),
    ('AVENUE', 'Kimwingu'),
    ('AVENUE', 'Kindayi'),
    ('AVENUE', 'Kindu'),
    ('AVENUE', 'Kindundu'),
    ('AVENUE', 'Kinduti'),
    ('AVENUE', 'Kingabwa'),
    ('AVENUE', 'Kingampika'),
    ('AVENUE', 'Kingotolo'),
    ('AVENUE', 'Kinguanda'),
    ('AVENUE', 'Kingunda'),
    ('AVENUE', 'Kingunzi'),
    ('AVENUE', 'Kinguzi'),
    ('AVENUE', 'Kinkoni'),
    ('AVENUE', 'Kinsaka'),
    ('AVENUE', 'Kinsaku'),
    ('AVENUE', 'Kinsamba'),
    ('AVENUE', 'Kinsambi'),
    ('AVENUE', 'Kinsele'),
    ('AVENUE', 'Kinshasa'),
    ('AVENUE', 'Kinsiona'),
    ('AVENUE', 'Kinsudi'),
    ('AVENUE', 'Kinsuka'),
    ('AVENUE', 'Kintete'),
    ('AVENUE', 'Kinvuta'),
    ('AVENUE', 'Kinzambi'),
    ('AVENUE', 'Kinzau'),
    ('AVENUE', 'Kinzazi'),
    ('AVENUE', 'Kinzengunzengu'),
    ('AVENUE', 'Kinzola'),
    ('AVENUE', 'Kinzuzi'),
    ('AVENUE', 'Kiobongoy'),
    ('AVENUE', 'Kiosi'),
    ('AVENUE', 'Kipaku'),
    ('AVENUE', 'Kipase'),
    ('AVENUE', 'Kipasi'),
    ('AVENUE', 'Kipata'),
    ('AVENUE', 'Kiri'),
    ('AVENUE', 'Kisangani'),
    ('AVENUE', 'Kisantu'),
    ('AVENUE', 'Kisolokele'),
    ('AVENUE', 'Kisombe'),
    ('AVENUE', 'Kitega'),
    ('AVENUE', 'Kitoko'),
    ('AVENUE', 'Kitomesa'),
    ('AVENUE', 'Kitona'),
    ('AVENUE', 'Kitoyi'),
    ('AVENUE', 'Kitundi'),
    ('AVENUE', 'Kivu'),
    ('AVENUE', 'Kivunda'),
    ('AVENUE', 'Kiwala'),
    ('AVENUE', 'Kiwaya'),
    ('AVENUE', 'Kodia'),
    ('AVENUE', 'Koko'),
    ('AVENUE', 'Kokolo'),
    ('AVENUE', 'Komoriko'),
    ('AVENUE', 'Kongolo'),
    ('AVENUE', 'Kubota'),
    ('AVENUE', 'Kulumba'),
    ('AVENUE', 'Kumba'),
    ('AVENUE', 'Kumbana'),
    ('AVENUE', 'Kumbi'),
    ('AVENUE', 'Kumbu'),
    ('AVENUE', 'Kundelungu'),
    ('AVENUE', 'Kunzulu'),
    ('AVENUE', 'Kusa'),
    ('AVENUE', 'Kutu'),
    ('AVENUE', 'Kwamouth'),
    ('AVENUE', 'Kwango'),
    ('AVENUE', 'Kwete'),
    ('AVENUE', 'Kwilu'),
    ('AVENUE', 'La Coline'),
    ('AVENUE', 'la Savane'),
    ('AVENUE', 'lac'),
    ('AVENUE', 'Lac Edouard'),
    ('AVENUE', 'Lac Lukamba'),
    ('AVENUE', 'Lac Tumba'),
    ('AVENUE', 'Lado'),
    ('AVENUE', 'Landa'),
    ('AVENUE', 'Landi'),
    ('AVENUE', 'Landu'),
    ('AVENUE', 'Langa Langa'),
    ('AVENUE', 'Lassa'),
    ('AVENUE', 'Le Bon Berger'),
    ('AVENUE', 'le Ngambu'),
    ('AVENUE', 'Lelo'),
    ('AVENUE', 'Lemba'),
    ('AVENUE', 'Lembi'),
    ('AVENUE', 'Leopold Sedar Senghor'),
    ('AVENUE', 'Leta'),
    ('AVENUE', 'Leza'),
    ('AVENUE', 'Libenge'),
    ('AVENUE', 'Libilimo'),
    ('AVENUE', 'Libinza'),
    ('AVENUE', 'Likasi'),
    ('AVENUE', 'Likinda'),
    ('AVENUE', 'Limaya'),
    ('AVENUE', 'Limba'),
    ('AVENUE', 'Limete'),
    ('AVENUE', 'Lingomo'),
    ('AVENUE', 'Lisala'),
    ('AVENUE', 'Lisasi 1'),
    ('AVENUE', 'Loango'),
    ('AVENUE', 'Lobo'),
    ('AVENUE', 'Lodja'),
    ('AVENUE', 'Logec'),
    ('AVENUE', 'Lokalama'),
    ('AVENUE', 'Lokele'),
    ('AVENUE', 'Lokonga'),
    ('AVENUE', 'Lokwa'),
    ('AVENUE', 'Loliki'),
    ('AVENUE', 'Lomami'),
    ('AVENUE', 'Looko'),
    ('AVENUE', 'Losimba-Bea'),
    ('AVENUE', 'Louange'),
    ('AVENUE', 'Lowa'),
    ('AVENUE', 'Lua'),
    ('AVENUE', 'Lualaba'),
    ('AVENUE', 'Luambo Makiadi'),
    ('AVENUE', 'Lubaki'),
    ('AVENUE', 'Lubefu'),
    ('AVENUE', 'Lubudi'),
    ('AVENUE', 'Lubula'),
    ('AVENUE', 'Lubumbashi'),
    ('AVENUE', 'Ludisi'),
    ('AVENUE', 'Luebo'),
    ('AVENUE', 'Luemba'),
    ('AVENUE', 'Luengi'),
    ('AVENUE', 'Lufu'),
    ('AVENUE', 'Luila'),
    ('AVENUE', 'Luila 1'),
    ('AVENUE', 'Lukandu'),
    ('AVENUE', 'Lukaya'),
    ('AVENUE', 'Lukelenge'),
    ('AVENUE', 'Lukengo'),
    ('AVENUE', 'Lukula'),
    ('AVENUE', 'Lukusa'),
    ('AVENUE', 'Lukwila'),
    ('AVENUE', 'Lumene'),
    ('AVENUE', 'LumiÃ¨re'),
    ('AVENUE', 'Lumumba'),
    ('AVENUE', 'Lunda'),
    ('AVENUE', 'Lundula'),
    ('AVENUE', 'Lunga'),
    ('AVENUE', 'Luozi'),
    ('AVENUE', 'Lupuku'),
    ('AVENUE', 'Lupuni'),
    ('AVENUE', 'Lusa'),
    ('AVENUE', 'Lusanga'),
    ('AVENUE', 'Lusenge'),
    ('AVENUE', 'Lushatsha'),
    ('AVENUE', 'Lusuki'),
    ('AVENUE', 'Lutondo'),
    ('AVENUE', 'Lutshatsha'),
    ('AVENUE', 'Lutunu'),
    ('AVENUE', 'Luvaka'),
    ('AVENUE', 'Luvemba'),
    ('AVENUE', 'Luvua'),
    ('AVENUE', 'Luyeye'),
    ('AVENUE', 'Luyi'),
    ('AVENUE', 'Luzizila'),
    ('AVENUE', 'Luzolanu'),
    ('AVENUE', 'Luzolo'),
    ('AVENUE', 'Mabele Mokonzi'),
    ('AVENUE', 'Mabengi'),
    ('AVENUE', 'Mabiala'),
    ('AVENUE', 'Mabika'),
    ('AVENUE', 'Mabiongo'),
    ('AVENUE', 'Maboto'),
    ('AVENUE', 'Madimba'),
    ('AVENUE', 'Madrandele'),
    ('AVENUE', 'Mafu'),
    ('AVENUE', 'Mai ndombe'),
    ('AVENUE', 'Maindombe'),
    ('AVENUE', 'Makanda manza'),
    ('AVENUE', 'Makanga'),
    ('AVENUE', 'Makanza'),
    ('AVENUE', 'Makasila'),
    ('AVENUE', 'Makasila2'),
    ('AVENUE', 'Makengo'),
    ('AVENUE', 'Makere'),
    ('AVENUE', 'Makoko'),
    ('AVENUE', 'Makola'),
    ('AVENUE', 'Makombo'),
    ('AVENUE', 'Makuala'),
    ('AVENUE', 'Makungu'),
    ('AVENUE', 'Malandi'),
    ('AVENUE', 'Malela'),
    ('AVENUE', 'Maluku'),
    ('AVENUE', 'Malundu'),
    ('AVENUE', 'Maluti'),
    ('AVENUE', 'Malweka'),
    ('AVENUE', 'maman sese'),
    ('AVENUE', 'Maman Yemo'),
    ('AVENUE', 'Mami Mwata'),
    ('AVENUE', 'Mamiekasay'),
    ('AVENUE', 'Mampasi'),
    ('AVENUE', 'Managua'),
    ('AVENUE', 'Manenga'),
    ('AVENUE', 'Mangana'),
    ('AVENUE', 'Mangele'),
    ('AVENUE', 'Mangembo'),
    ('AVENUE', 'mangengenge'),
    ('AVENUE', 'Mango'),
    ('AVENUE', 'Manguiers'),
    ('AVENUE', 'Maniema'),
    ('AVENUE', 'Maniema 1'),
    ('AVENUE', 'Maniema 2'),
    ('AVENUE', 'Maniema 3'),
    ('AVENUE', 'Manoka'),
    ('AVENUE', 'Manzambaya'),
    ('AVENUE', 'Manzengele'),
    ('AVENUE', 'Mapende'),
    ('AVENUE', 'Marche'),
    ('AVENUE', 'Marie-JosÃ©e'),
    ('AVENUE', 'Marine'),
    ('AVENUE', 'Maringa'),
    ('AVENUE', 'Martin Ekanda'),
    ('AVENUE', 'Masamukini'),
    ('AVENUE', 'Masasu'),
    ('AVENUE', 'Maseki'),
    ('AVENUE', 'Masiala'),
    ('AVENUE', 'Masikita'),
    ('AVENUE', 'Masimanimba'),
    ('AVENUE', 'Masimaninba'),
    ('AVENUE', 'Masinde'),
    ('AVENUE', 'Maso Lokele'),
    ('AVENUE', 'Massamba'),
    ('AVENUE', 'Massano'),
    ('AVENUE', 'Matadi'),
    ('AVENUE', 'Matadi Mayo'),
    ('AVENUE', 'Mateba'),
    ('AVENUE', 'Matiaba'),
    ('AVENUE', 'Matiti'),
    ('AVENUE', 'Matondo'),
    ('AVENUE', 'Matuba'),
    ('AVENUE', 'Matumona'),
    ('AVENUE', 'Mavanga'),
    ('AVENUE', 'Mavungu'),
    ('AVENUE', 'Mawanga'),
    ('AVENUE', 'Mawazo'),
    ('AVENUE', 'Mawi'),
    ('AVENUE', 'Mayala'),
    ('AVENUE', 'mayalos'),
    ('AVENUE', 'Mayanda'),
    ('AVENUE', 'Mayangi'),
    ('AVENUE', 'Mayemba'),
    ('AVENUE', 'Mayika'),
    ('AVENUE', 'Mayimpili'),
    ('AVENUE', 'Mayinda'),
    ('AVENUE', 'Mayobo'),
    ('AVENUE', 'Mayoko'),
    ('AVENUE', 'Mayulu'),
    ('AVENUE', 'Mayuma'),
    ('AVENUE', 'Mazengele'),
    ('AVENUE', 'Mazout'),
    ('AVENUE', 'MaÂ¨-Ndombe'),
    ('AVENUE', 'MaÃ§on'),
    ('AVENUE', 'Mbadi'),
    ('AVENUE', 'Mbakana'),
    ('AVENUE', 'Mbala'),
    ('AVENUE', 'Mbama'),
    ('AVENUE', 'Mbambi'),
    ('AVENUE', 'Mbandaka'),
    ('AVENUE', 'Mbandaka 2'),
    ('AVENUE', 'Mbange'),
    ('AVENUE', 'Mbanza'),
    ('AVENUE', 'Mbanza Boma'),
    ('AVENUE', 'Mbanza Ngungu'),
    ('AVENUE', 'Mbanza-Boma'),
    ('AVENUE', 'Mbaya'),
    ('AVENUE', 'Mbee'),
    ('AVENUE', 'Mbengo'),
    ('AVENUE', 'Mbenza'),
    ('AVENUE', 'Mbimbu'),
    ('AVENUE', 'Mbimi'),
    ('AVENUE', 'Mbimi I'),
    ('AVENUE', 'Mbimi II'),
    ('AVENUE', 'Mbinza'),
    ('AVENUE', 'Mbole'),
    ('AVENUE', 'Mboloko'),
    ('AVENUE', 'Mbombo'),
    ('AVENUE', 'Mbomu'),
    ('AVENUE', 'Mbuji-Mayi'),
    ('AVENUE', 'Mbujimayi 3'),
    ('AVENUE', 'Mbuku'),
    ('AVENUE', 'Mbunza'),
    ('AVENUE', 'Mbuyi'),
    ('AVENUE', 'Mbwaki'),
    ('AVENUE', 'MbÃ» Marie'),
    ('AVENUE', 'Menga'),
    ('AVENUE', 'Metalurgie'),
    ('AVENUE', 'Mfumu Mvula'),
    ('AVENUE', 'Mfumu Nsaka'),
    ('AVENUE', 'Mfuti'),
    ('AVENUE', 'Mgr. Kimbombo'),
    ('AVENUE', 'Mgr. Kimbondo'),
    ('AVENUE', 'Mianda'),
    ('AVENUE', 'Mika'),
    ('AVENUE', 'Mikala'),
    ('AVENUE', 'Milambo'),
    ('AVENUE', 'Milelegani'),
    ('AVENUE', 'Mingele'),
    ('AVENUE', 'Minikongo'),
    ('AVENUE', 'Miningulu'),
    ('AVENUE', 'Mission FranÃ§aise'),
    ('AVENUE', 'Mitendi'),
    ('AVENUE', 'Mobiango'),
    ('AVENUE', 'Moboma'),
    ('AVENUE', 'Mobonda'),
    ('AVENUE', 'Mobutu'),
    ('AVENUE', 'Molende'),
    ('AVENUE', 'Mombele'),
    ('AVENUE', 'Mombesa'),
    ('AVENUE', 'momboy'),
    ('AVENUE', 'Momina'),
    ('AVENUE', 'Mompoy'),
    ('AVENUE', 'Mondo'),
    ('AVENUE', 'Mongala'),
    ('AVENUE', 'Mongata'),
    ('AVENUE', 'Mongoluala'),
    ('AVENUE', 'Monkole'),
    ('AVENUE', 'Monokaka'),
    ('AVENUE', 'Monsuaya'),
    ('AVENUE', 'Mopulu'),
    ('AVENUE', 'Mosala'),
    ('AVENUE', 'Mosambo'),
    ('AVENUE', 'Moseni'),
    ('AVENUE', 'Mosete Mbombo'),
    ('AVENUE', 'Motel FIKIN'),
    ('AVENUE', 'Moto Na Moto'),
    ('AVENUE', 'Moussosso'),
    ('AVENUE', 'moyo'),
    ('AVENUE', 'Mpangala'),
    ('AVENUE', 'Mpasi'),
    ('AVENUE', 'Mpeti'),
    ('AVENUE', 'Mpika'),
    ('AVENUE', 'Mpila'),
    ('AVENUE', 'Mpolo'),
    ('AVENUE', 'Mpoyi'),
    ('AVENUE', 'Mpozo'),
    ('AVENUE', 'Mpumbu'),
    ('AVENUE', 'MSF'),
    ('AVENUE', 'Muai Kabare'),
    ('AVENUE', 'Muala Kizende'),
    ('AVENUE', 'Muanawuta'),
    ('AVENUE', 'Muanda'),
    ('AVENUE', 'Muanza'),
    ('AVENUE', 'Mubenga'),
    ('AVENUE', 'Mubiala'),
    ('AVENUE', 'Muemalo'),
    ('AVENUE', 'Mufundu'),
    ('AVENUE', 'Muka'),
    ('AVENUE', 'Mukadi'),
    ('AVENUE', 'Mukanya'),
    ('AVENUE', 'Mukoko'),
    ('AVENUE', 'Mukonzo'),
    ('AVENUE', 'Mukubwa'),
    ('AVENUE', 'Mukueti'),
    ('AVENUE', 'Mukwala'),
    ('AVENUE', 'Mulamba'),
    ('AVENUE', 'Mulano'),
    ('AVENUE', 'Mulele'),
    ('AVENUE', 'Mumbembe'),
    ('AVENUE', 'Mundjana'),
    ('AVENUE', 'Munga'),
    ('AVENUE', 'Munoki'),
    ('AVENUE', 'Munongo'),
    ('AVENUE', 'Muntuadi'),
    ('AVENUE', 'Mupwela'),
    ('AVENUE', 'Musamba'),
    ('AVENUE', 'Musango'),
    ('AVENUE', 'Mushi'),
    ('AVENUE', 'Mutombo Katshi'),
    ('AVENUE', 'Mutoto'),
    ('AVENUE', 'Mvula'),
    ('AVENUE', 'Mvunzi'),
    ('AVENUE', 'Mwadingusha'),
    ('AVENUE', 'Mwamini'),
    ('AVENUE', 'Mwanga'),
    ('AVENUE', 'Mwanza'),
    ('AVENUE', 'Mweka'),
    ('AVENUE', 'Mwela'),
    ('AVENUE', 'Mwene-Ditu'),
    ('AVENUE', 'Mwenzi'),
    ('AVENUE', 'Mwepu'),
    ('AVENUE', 'Mweze'),
    ('AVENUE', 'Nangami Kongo'),
    ('AVENUE', 'Nation'),
    ('AVENUE', 'Nations Unies'),
    ('AVENUE', 'Nawazawadio'),
    ('AVENUE', 'Ndala'),
    ('AVENUE', 'Ndanu'),
    ('AVENUE', 'Ndelo 2'),
    ('AVENUE', 'Ndembo'),
    ('AVENUE', 'Ndona'),
    ('AVENUE', 'Nduanunu'),
    ('AVENUE', 'Nduisi'),
    ('AVENUE', 'Ndumana'),
    ('AVENUE', 'Ndunga'),
    ('AVENUE', 'Ngaboko'),
    ('AVENUE', 'Ngafani'),
    ('AVENUE', 'Ngaliema'),
    ('AVENUE', 'Ngambali'),
    ('AVENUE', 'Ngampagnie'),
    ('AVENUE', 'Nganda malala'),
    ('AVENUE', 'Nganga'),
    ('AVENUE', 'Nganguele'),
    ('AVENUE', 'Ngangwele'),
    ('AVENUE', 'Ngeba'),
    ('AVENUE', 'Ngina'),
    ('AVENUE', 'Ngiri-Ngiri'),
    ('AVENUE', 'Ngombi'),
    ('AVENUE', 'Ngongo Lutete'),
    ('AVENUE', 'Ngowa'),
    ('AVENUE', 'Ngoyulu'),
    ('AVENUE', 'Nguma'),
    ('AVENUE', 'Ngungu'),
    ('AVENUE', 'Nguya'),
    ('AVENUE', 'Ngwala'),
    ('AVENUE', 'Ngwizani'),
    ('AVENUE', 'Nino'),
    ('AVENUE', 'Nioka'),
    ('AVENUE', 'Nioki'),
    ('AVENUE', 'Niwa'),
    ('AVENUE', 'Nkana'),
    ('AVENUE', 'Nkoli'),
    ('AVENUE', 'Nkumu'),
    ('AVENUE', 'Nsanga'),
    ('AVENUE', 'Nseka'),
    ('AVENUE', 'Nseke'),
    ('AVENUE', 'Nsele'),
    ('AVENUE', 'Nsilulu'),
    ('AVENUE', 'Nsonakulu'),
    ('AVENUE', 'Nsondi'),
    ('AVENUE', 'Nsongi'),
    ('AVENUE', 'Nsonsa'),
    ('AVENUE', 'Nsuala'),
    ('AVENUE', 'Nsubuka'),
    ('AVENUE', 'Nsumbu'),
    ('AVENUE', 'Nsundi'),
    ('AVENUE', 'Ntangu'),
    ('AVENUE', 'Ntantu'),
    ('AVENUE', 'Ntombola'),
    ('AVENUE', 'Ntotila'),
    ('AVENUE', 'Ntunu'),
    ('AVENUE', 'Nyamaseko'),
    ('AVENUE', 'Nyanguile'),
    ('AVENUE', 'Nyangwe'),
    ('AVENUE', 'Nyembo'),
    ('AVENUE', 'Nzenga'),
    ('AVENUE', 'Nzeza Landu'),
    ('AVENUE', 'Nzilo'),
    ('AVENUE', 'Nzita'),
    ('AVENUE', 'Nzoigba'),
    ('AVENUE', 'Nzoloko'),
    ('AVENUE', 'OCC'),
    ('AVENUE', 'Okapi'),
    ('AVENUE', 'Okito'),
    ('AVENUE', 'Okitundu'),
    ('AVENUE', 'Omedji'),
    ('AVENUE', 'Omekongo-Safi'),
    ('AVENUE', 'Omo'),
    ('AVENUE', 'Opala'),
    ('AVENUE', 'orientation I'),
    ('AVENUE', 'Panzi'),
    ('AVENUE', 'Papa Ileo'),
    ('AVENUE', 'Parc'),
    ('AVENUE', 'Parc Virunga'),
    ('AVENUE', 'Parlement'),
    ('AVENUE', 'Paroisse'),
    ('AVENUE', 'Pasi'),
    ('AVENUE', 'Pecheur'),
    ('AVENUE', 'petit petit'),
    ('AVENUE', 'Petronie'),
    ('AVENUE', 'Pharmaco'),
    ('AVENUE', 'Photopao'),
    ('AVENUE', 'Pic nic'),
    ('AVENUE', 'Pierre Elengesa'),
    ('AVENUE', 'Pinzi'),
    ('AVENUE', 'Piroguier'),
    ('AVENUE', 'Plateau'),
    ('AVENUE', 'Poko'),
    ('AVENUE', 'Ponzi'),
    ('AVENUE', 'Province'),
    ('AVENUE', 'PrÃ©montrÃ©'),
    ('AVENUE', 'Pululu'),
    ('AVENUE', 'Pumbu'),
    ('AVENUE', 'PÃ¨re Boka'),
    ('AVENUE', 'PÃ©cheur'),
    ('AVENUE', 'Radio'),
    ('AVENUE', 'Rails'),
    ('AVENUE', 'Regideso'),
    ('AVENUE', 'Revolution'),
    ('AVENUE', 'Ring'),
    ('AVENUE', 'Riviera'),
    ('AVENUE', 'Rodebi'),
    ('AVENUE', 'Roi Baudoin'),
    ('AVENUE', 'rout de matadi 2'),
    ('AVENUE', 'Rufidji'),
    ('AVENUE', 'Ruytter'),
    ('AVENUE', 'Ruzizi'),
    ('AVENUE', 'Rwakadingi'),
    ('AVENUE', 'RÃ©verend Mbuala'),
    ('AVENUE', 'RÃ©volution'),
    ('AVENUE', 'SabliÃ¨re'),
    ('AVENUE', 'Sabrina'),
    ('AVENUE', 'Safi'),
    ('AVENUE', 'Saint Christophe'),
    ('AVENUE', 'Saio'),
    ('AVENUE', 'Sakania'),
    ('AVENUE', 'Sakuru'),
    ('AVENUE', 'Salongo 1'),
    ('AVENUE', 'Salongo 2'),
    ('AVENUE', 'Salongo 3'),
    ('AVENUE', 'Sama'),
    ('AVENUE', 'Samani'),
    ('AVENUE', 'Sanga'),
    ('AVENUE', 'Sankara'),
    ('AVENUE', 'Sankuru'),
    ('AVENUE', 'Sans nom'),
    ('AVENUE', 'Sanzu'),
    ('AVENUE', 'Saturne'),
    ('AVENUE', 'Sefu'),
    ('AVENUE', 'Sendwe'),
    ('AVENUE', 'Senga'),
    ('AVENUE', 'SEP'),
    ('AVENUE', 'SEP Congo'),
    ('AVENUE', 'Sergent Moke'),
    ('AVENUE', 'Severine'),
    ('AVENUE', 'Shaba'),
    ('AVENUE', 'Sikama'),
    ('AVENUE', 'Soki'),
    ('AVENUE', 'Sokwela'),
    ('AVENUE', 'Sombele'),
    ('AVENUE', 'Sonabata'),
    ('AVENUE', 'Songesa'),
    ('AVENUE', 'Songi'),
    ('AVENUE', 'Songoli'),
    ('AVENUE', 'source'),
    ('AVENUE', 'Soweto'),
    ('AVENUE', 'Suisse'),
    ('AVENUE', 'Sukama'),
    ('AVENUE', 'Sukambundu'),
    ('AVENUE', 'Sumaili'),
    ('AVENUE', 'Sumbi'),
    ('AVENUE', 'Table Ronde'),
    ('AVENUE', 'Tanganika'),
    ('AVENUE', 'Tanganyika'),
    ('AVENUE', 'Tango'),
    ('AVENUE', 'Tanuisia'),
    ('AVENUE', 'Tavoka'),
    ('AVENUE', 'Tchikuya'),
    ('AVENUE', 'Teke'),
    ('AVENUE', 'Telecom'),
    ('AVENUE', 'Television'),
    ('AVENUE', 'Tende'),
    ('AVENUE', 'Tendele'),
    ('AVENUE', 'Terminus'),
    ('AVENUE', 'Terrain'),
    ('AVENUE', 'THTCC Inga-Kolwezi'),
    ('AVENUE', 'Tinta'),
    ('AVENUE', 'Tissakin'),
    ('AVENUE', 'Titule'),
    ('AVENUE', 'Toko'),
    ('AVENUE', 'Tomba'),
    ('AVENUE', 'Tombalbaye'),
    ('AVENUE', 'Tombe'),
    ('AVENUE', 'Tombo'),
    ('AVENUE', 'Tonde'),
    ('AVENUE', 'Tourisme'),
    ('AVENUE', 'Transversale'),
    ('AVENUE', 'tribunal'),
    ('AVENUE', 'Trois VallÃ©es'),
    ('AVENUE', 'Tshiala Mwana'),
    ('AVENUE', 'Tshilenge'),
    ('AVENUE', 'Tshimanga'),
    ('AVENUE', 'Tshisumpa'),
    ('AVENUE', 'Tshitenge'),
    ('AVENUE', 'Tshiungu'),
    ('AVENUE', 'Tshopo'),
    ('AVENUE', 'Tsobe'),
    ('AVENUE', 'Tubutu'),
    ('AVENUE', 'Tukakongo'),
    ('AVENUE', 'Tulembele'),
    ('AVENUE', 'Tumba'),
    ('AVENUE', 'Tungadio'),
    ('AVENUE', 'Tungila'),
    ('AVENUE', 'Tute'),
    ('AVENUE', 'Tyranus'),
    ('AVENUE', 'Uele'),
    ('AVENUE', 'Umangi'),
    ('AVENUE', 'Usoke'),
    ('AVENUE', 'Uvira'),
    ('AVENUE', 'Vale'),
    ('AVENUE', 'Vangu'),
    ('AVENUE', 'Viaza'),
    ('AVENUE', 'Vive Congo'),
    ('AVENUE', 'Voka'),
    ('AVENUE', 'Volcan'),
    ('AVENUE', 'Vundulu 1'),
    ('AVENUE', 'Vundulu 2'),
    ('AVENUE', 'Vundulu 3'),
    ('AVENUE', 'VÃ©nus'),
    ('AVENUE', 'Wagenia'),
    ('AVENUE', 'Wamba'),
    ('AVENUE', 'Wanba 3'),
    ('AVENUE', 'Wando'),
    ('AVENUE', 'Wangata'),
    ('AVENUE', 'Wombali'),
    ('AVENUE', 'Wunga'),
    ('AVENUE', 'Yakahumbu'),
    ('AVENUE', 'Yakamo'),
    ('AVENUE', 'Yamaha'),
    ('AVENUE', 'Yamayama'),
    ('AVENUE', 'Yandonge'),
    ('AVENUE', 'Yangambi'),
    ('AVENUE', 'Yasa'),
    ('AVENUE', 'Yoka'),
    ('AVENUE', 'Yoko'),
    ('AVENUE', 'Yolo'),
    ('AVENUE', 'Yonso'),
    ('AVENUE', 'Yoseki'),
    ('AVENUE', 'Yowalola'),
    ('AVENUE', 'Yumbu'),
    ('AVENUE', 'Zaba'),
    ('AVENUE', 'Zamba'),
    ('AVENUE', 'Zando'),
    ('AVENUE', 'Zeka'),
    ('AVENUE', 'Zola'),
    ('AVENUE', 'Zolana'),
    ('AVENUE', 'Zongo'),
    ('AVENUE', 'Zongo Ntolo'),
    ('AVENUE', 'Ã\x89mile Ngoy'),
]

KINSHASA_AVENUES_BY_COMMUNE: dict[str, list[tuple[str, str]]] = {
    'Gombe': [
        ('AVENUE', 'a.a services road'),
        ('AVENUE', 'admin'),
        ('AVENUE', 'Avecnue des ambassadeur'),
        ('AVENUE', 'Barwal'),
        ('AVENUE', 'Bas-Congo'),
        ('AVENUE', 'Basoko'),
        ('AVENUE', 'biochem dept'),
        ('AVENUE', 'Boyata'),
        ('AVENUE', 'BYE PASS ROAD'),
        ('AVENUE', 'C.S CLOSE'),
        ('AVENUE', "Caisse d'Epargne"),
        ('AVENUE', 'chapel road'),
        ('AVENUE', 'Claude Maluma'),
        ('AVENUE', 'Colonel Ebeya'),
        ('AVENUE', 'Colonel Lukusa'),
        ('AVENUE', 'commercial area track road'),
        ('AVENUE', 'Complex Road'),
        ('AVENUE', "d'Isiro"),
        ('AVENUE', 'de Kalemie'),
        ('AVENUE', "de l'Hopital"),
        ('AVENUE', 'de l’Hôpital'),
        ('AVENUE', "de l'OMS"),
        ('AVENUE', 'de l’Ouganda'),
        ('AVENUE', 'de l’École'),
        ('AVENUE', "de l'Équateur"),
        ('AVENUE', 'de la Douane'),
        ('AVENUE', 'de la Gombe'),
        ('AVENUE', 'de la Justice'),
        ('AVENUE', 'de la Libération'),
        ('AVENUE', 'de la Mission'),
        ('AVENUE', 'de la Mongala'),
        ('AVENUE', 'de la Paix'),
        ('AVENUE', 'de la Presse'),
        ('AVENUE', 'de la Science'),
        ('AVENUE', 'de la T.S.F.'),
        ('AVENUE', 'de la Vallée'),
        ('AVENUE', 'de Mushie'),
        ('AVENUE', 'des ambassadeur'),
        ('AVENUE', 'des Ambassadeurs'),
        ('AVENUE', 'des Aviateurs'),
        ('AVENUE', 'des Batetela'),
        ('AVENUE', 'Des batoniers'),
        ('AVENUE', 'des Cataractes'),
        ('AVENUE', 'des Citronniers'),
        ('AVENUE', 'des Cliniques'),
        ('AVENUE', 'des Coteaux'),
        ('AVENUE', 'des Flamboyants'),
        ('AVENUE', 'des Forces Armées'),
        ('AVENUE', 'des Huileries'),
        ('AVENUE', 'des Jacarandas'),
        ('AVENUE', 'des Monts Virunga'),
        ('AVENUE', 'des Nations Unies'),
        ('AVENUE', 'des Palmiers'),
        ('AVENUE', 'des Sénégalais'),
        ('AVENUE', 'des Vieillards'),
        ('AVENUE', 'des Étoiles'),
        ('AVENUE', 'diploma path'),
        ('AVENUE', 'Dongo'),
        ('AVENUE', 'Dracena'),
        ('AVENUE', 'du 30 Juin'),
        ('AVENUE', 'du Bandundu'),
        ('AVENUE', 'du Bas-Congo'),
        ('AVENUE', 'du Canal'),
        ('AVENUE', 'du Cercle'),
        ('AVENUE', 'du Cocotier'),
        ('AVENUE', 'du Colonel Tshatshi'),
        ('AVENUE', 'du Comité urbain'),
        ('AVENUE', 'du Commerce'),
        ('AVENUE', 'du Fleuve'),
        ('AVENUE', 'du Haut Commandement'),
        ('AVENUE', 'du Haut-Congo'),
        ('AVENUE', 'du Kasaï'),
        ('AVENUE', 'du Livre'),
        ('AVENUE', 'du Marais'),
        ('AVENUE', 'du Marché'),
        ('AVENUE', 'du Mont des Arts'),
        ('AVENUE', 'du Petit pont'),
        ('AVENUE', 'du Plateau'),
        ('AVENUE', 'du Pont'),
        ('AVENUE', 'du Port'),
        ('AVENUE', 'du Roi Baudoin'),
        ('AVENUE', 'du Roi Baudouin'),
        ('AVENUE', 'du Syndicat'),
        ('AVENUE', 'du Tchad'),
        ('AVENUE', 'Dukku road'),
        ('AVENUE', 'Dumi'),
        ('AVENUE', 'ECWA CHURCH HAUSA ROAD'),
        ('AVENUE', 'ENTERPRENEUSHIP WAY'),
        ('AVENUE', 'Fed secretariat road'),
        ('AVENUE', 'female hostel ent. path'),
        ('AVENUE', 'female hostel foot path'),
        ('AVENUE', 'female hostel path'),
        ('AVENUE', 'Flambeau'),
        ('AVENUE', 'foot'),
        ('AVENUE', 'Galerie Présidentielle'),
        ('AVENUE', 'Gemena'),
        ('AVENUE', 'Goje Street'),
        ('AVENUE', 'Goma'),
        ('AVENUE', 'Gombe - Biu Road'),
        ('AVENUE', 'Gombe - Potiskum Road'),
        ('AVENUE', 'Gombe - Potiskum Road; Ashaka Bajago Road'),
        ('AVENUE', 'GOMBE - YOLA ROAD'),
        ('AVENUE', 'Gombe state university road'),
        ('AVENUE', 'green path'),
        ('AVENUE', 'Grema Mustapha Road'),
        ('AVENUE', 'GSU ROAD'),
        ('AVENUE', 'Gécamines'),
        ('AVENUE', 'hall entrance'),
        ('AVENUE', 'hostel path'),
        ('AVENUE', 'ict'),
        ('AVENUE', 'IDI streat'),
        ('AVENUE', 'Ipenge'),
        ('AVENUE', 'Itaga'),
        ('AVENUE', 'Jauro Bappi Street'),
        ('AVENUE', 'Jirgin na yaya street'),
        ('AVENUE', 'Kabasele Tshiamala Joseph'),
        ('AVENUE', 'Kalembelembe'),
        ('AVENUE', 'Kalume Mwana Kahambwa'),
        ('AVENUE', 'Kanga'),
        ('AVENUE', 'Kasa-Vubu'),
        ('AVENUE', 'Kasongo'),
        ('AVENUE', 'Kasuwan Kifi street'),
        ('AVENUE', 'KASUWAN MATA ROAD'),
        ('AVENUE', 'Katanga'),
        ('AVENUE', 'Kauka'),
        ('AVENUE', 'kawuka'),
        ('AVENUE', 'Kidicho'),
        ('AVENUE', 'Kilo-Moto'),
        ('AVENUE', 'Kilolo Musamba Lubemba'),
        ('AVENUE', 'Kisangani'),
        ('AVENUE', 'Kitoko'),
        ('AVENUE', 'Kitona'),
        ('AVENUE', 'KUNDULUN ROAD'),
        ('AVENUE', 'Kwango'),
        ('AVENUE', 'Layin tare'),
        ('AVENUE', 'le Ngambu'),
        ('AVENUE', 'library path'),
        ('AVENUE', 'Likasi'),
        ('AVENUE', 'Lodja'),
        ('AVENUE', 'Lokele'),
        ('AVENUE', 'Lokonga'),
        ('AVENUE', 'Luambo Makiadi'),
        ('AVENUE', 'Lubefu'),
        ('AVENUE', 'lutumba'),
        ('AVENUE', 'Malam Kuri Riyal Road'),
        ('AVENUE', 'male hostel path'),
        ('AVENUE', 'Market Way'),
        ('AVENUE', 'Mbuji-Mayi'),
        ('AVENUE', 'Milambo'),
        ('AVENUE', 'Mpeti'),
        ('AVENUE', 'Mpolo'),
        ('AVENUE', 'Muai Kabare'),
        ('AVENUE', 'Mutombo Katshi'),
        ('AVENUE', 'Mutum Daya to Filiya Road'),
        ('AVENUE', 'Mwene-Ditu'),
        ('AVENUE', 'Nassarawo Road'),
        ('AVENUE', 'Ngongo Lutete'),
        ('AVENUE', 'Nioki'),
        ('AVENUE', 'Nyembo'),
        ('AVENUE', 'Okito'),
        ('AVENUE', 'Out'),
        ('AVENUE', 'Pantami Road'),
        ('AVENUE', 'Papa Ileo'),
        ('AVENUE', 'PGD WAY'),
        ('AVENUE', 'Pierre boka'),
        ('AVENUE', "Place de l'Indépendance"),
        ('AVENUE', 'Place de la Gare'),
        ('AVENUE', 'Place de la Justice'),
        ('AVENUE', 'Place de la République'),
        ('AVENUE', 'Place du 27 Octobre'),
        ('AVENUE', 'Place du Marché Central'),
        ('AVENUE', 'Place du Soldat Congolais'),
        ('AVENUE', 'Place Royal'),
        ('AVENUE', 'Plateau'),
        ('AVENUE', 'plato street'),
        ('AVENUE', 'point one kwanan Alheri, Gona Div'),
        ('AVENUE', 'Promenade de la Raquette'),
        ('AVENUE', 'Province'),
        ('AVENUE', 'Pumbu'),
        ('AVENUE', 'Père Boka'),
        ('AVENUE', 'Roads'),
        ('AVENUE', 'Roi Baudoin'),
        ('AVENUE', "Rond-Point de l'Afrique Centrale"),
        ('AVENUE', 'Rwakadingi'),
        ('AVENUE', 'Révolution'),
        ('AVENUE', 'Sabon Line Street'),
        ('AVENUE', 'Saut-de-Mouton'),
        ('AVENUE', 'Sergent Moke'),
        ('AVENUE', 'Shehu Abubakar Road'),
        ('AVENUE', 'Tombalbaye'),
        ('AVENUE', 'TUKULMA ROAD'),
        ('AVENUE', 'TUMU KASHERE ROAD'),
        ('AVENUE', 'Uban bala street'),
        ('AVENUE', 'Uvira'),
        ('AVENUE', 'W/KESA-M/INNA ROAD'),
        ('AVENUE', 'Wagenia'),
        ('AVENUE', 'Wangata'),
        ('AVENUE', 'Zongo Ntolo'),
        ('AVENUE', 'zoo road'),
        ('AVENUE', 'Zubairu Bn Auwam Close'),
        ('AVENUE', 'zubairu bn auwam Way'),
        ('RUE', 'Adama'),
        ('RUE', 'Bomu'),
        ('RUE', 'de Basankusu'),
        ('RUE', 'de la Concorde'),
        ('RUE', 'de Luisa'),
        ('RUE', 'de rivière'),
        ('RUE', 'des Fleurs'),
        ('RUE', 'des Lilas'),
    ],
    'Kalamu': [
        ('AVENUE', '10e Rue'),
        ('AVENUE', '11e Rue'),
        ('AVENUE', '12e Rue'),
        ('AVENUE', '13e Rue'),
        ('AVENUE', '13ème Rue'),
        ('AVENUE', '14e Rue'),
        ('AVENUE', '15ème rue'),
        ('AVENUE', '16ème rue'),
        ('AVENUE', '17e Rue'),
        ('AVENUE', '18e Rue'),
        ('AVENUE', '19e Rue'),
        ('AVENUE', '1ère Rue'),
        ('AVENUE', '20e Rue'),
        ('AVENUE', '21e Rue'),
        ('AVENUE', '22e Rue'),
        ('AVENUE', '2ème Rue'),
        ('AVENUE', '3ème Rue'),
        ('AVENUE', '4ème Rue'),
        ('AVENUE', '6ème rue'),
        ('AVENUE', '6ème rue Bis'),
        ('AVENUE', '7ème Rue'),
        ('AVENUE', '7ème Rue Bis'),
        ('AVENUE', '8e Rue'),
        ('AVENUE', '8ème Rue'),
        ('AVENUE', '9e Rue'),
        ('AVENUE', 'Badjoko'),
        ('AVENUE', 'Bakusu'),
        ('AVENUE', 'Bakwandumu'),
        ('AVENUE', 'bambelota'),
        ('AVENUE', 'Bambu'),
        ('AVENUE', 'Banalia'),
        ('AVENUE', 'Bandulugu'),
        ('AVENUE', 'Baobab'),
        ('AVENUE', 'Basuku'),
        ('AVENUE', 'Belladone'),
        ('AVENUE', 'Benkana'),
        ('AVENUE', 'Bokiba'),
        ('AVENUE', 'Bokote'),
        ('AVENUE', 'Bonga'),
        ('AVENUE', 'Bongi'),
        ('AVENUE', 'Bongolo'),
        ('AVENUE', 'Bordane'),
        ('AVENUE', 'Buburu'),
        ('AVENUE', 'Bukeyi'),
        ('AVENUE', 'Cafeier'),
        ('AVENUE', 'Camp Pinzi'),
        ('AVENUE', 'Cendre'),
        ('AVENUE', 'Chaussée de Kimwenza'),
        ('AVENUE', 'Cito'),
        ('AVENUE', 'Citroniers'),
        ('AVENUE', 'Cocotiers'),
        ('AVENUE', 'Colonelle lukusa'),
        ('AVENUE', 'Cottoniers'),
        ('AVENUE', 'Cypres'),
        ('AVENUE', 'Dahlas'),
        ('AVENUE', 'de l’Université'),
        ('AVENUE', "de l'Église"),
        ('AVENUE', 'de la Permanence'),
        ('AVENUE', 'de la Victoire'),
        ('AVENUE', 'de Lokalama'),
        ('AVENUE', 'Direction Lumumba'),
        ('AVENUE', 'Dispensaire'),
        ('AVENUE', 'du Stade'),
        ('AVENUE', 'Dubumani'),
        ('AVENUE', 'Duma'),
        ('AVENUE', 'Elengesa'),
        ('AVENUE', 'Enseignement'),
        ('AVENUE', 'Ezo'),
        ('AVENUE', 'Flora'),
        ('AVENUE', 'Gindu'),
        ('AVENUE', 'Goa'),
        ('AVENUE', 'Henri Bongolo'),
        ('AVENUE', 'Hôpital'),
        ('AVENUE', 'Infirmier'),
        ('AVENUE', 'Ingende'),
        ('AVENUE', 'Inzia'),
        ('AVENUE', 'Kalengo'),
        ('AVENUE', 'Kanda kanda'),
        ('AVENUE', 'Kapela'),
        ('AVENUE', 'Kasa-Vubu'),
        ('AVENUE', 'Kase Vubu'),
        ('AVENUE', 'Kembe'),
        ('AVENUE', 'Kimondo'),
        ('AVENUE', 'Kimpwanza'),
        ('AVENUE', 'Kimwenza'),
        ('AVENUE', 'Kingunda'),
        ('AVENUE', 'Kinsudi'),
        ('AVENUE', 'Kinzuzi'),
        ('AVENUE', 'Kitona'),
        ('AVENUE', 'Kola'),
        ('AVENUE', 'Kolas'),
        ('AVENUE', 'Kwilu'),
        ('AVENUE', 'Laurirs'),
        ('AVENUE', 'Limete'),
        ('AVENUE', 'Lisala'),
        ('AVENUE', 'Lokalama'),
        ('AVENUE', 'Lokolenge'),
        ('AVENUE', 'Longo'),
        ('AVENUE', 'Longo I'),
        ('AVENUE', 'Longo II'),
        ('AVENUE', 'Longo III'),
        ('AVENUE', 'Longo IV'),
        ('AVENUE', 'Luambo Makiadi'),
        ('AVENUE', 'Lufungula'),
        ('AVENUE', 'Luila'),
        ('AVENUE', 'Lukala'),
        ('AVENUE', 'Lukamawa'),
        ('AVENUE', 'Lumumba'),
        ('AVENUE', 'Luozi'),
        ('AVENUE', 'Mabika'),
        ('AVENUE', 'Makere'),
        ('AVENUE', 'Malembe'),
        ('AVENUE', 'Manguiers'),
        ('AVENUE', 'Marais'),
        ('AVENUE', 'Mateba'),
        ('AVENUE', 'Mbole'),
        ('AVENUE', 'Miningulu'),
        ('AVENUE', 'Mombesa'),
        ('AVENUE', 'Mompono'),
        ('AVENUE', 'Mompoy'),
        ('AVENUE', 'Movena'),
        ('AVENUE', 'Mpozo'),
        ('AVENUE', 'Nfumunvula'),
        ('AVENUE', 'Ngaliema'),
        ('AVENUE', 'Ngangwele'),
        ('AVENUE', 'Ngeba'),
        ('AVENUE', 'Ngiri ngiri'),
        ('AVENUE', 'Nioki'),
        ('AVENUE', 'Orangers'),
        ('AVENUE', 'Palmiers'),
        ('AVENUE', 'Petit Boulevard Résidentiel'),
        ('AVENUE', "Place d'Aru"),
        ('AVENUE', 'Place Gaya'),
        ('AVENUE', 'Poko'),
        ('AVENUE', 'Prevoyance'),
        ('AVENUE', 'Quartier limete'),
        ('AVENUE', 'Rond-Point Ezo'),
        ('AVENUE', 'Ruelle Sasa'),
        ('AVENUE', 'Sakania'),
        ('AVENUE', 'Sendwe'),
        ('AVENUE', 'Simba'),
        ('AVENUE', 'Sports'),
        ('AVENUE', 'Sécurité'),
        ('AVENUE', 'Tende'),
        ('AVENUE', 'Triomphal'),
        ('AVENUE', 'Wando'),
        ('AVENUE', 'Watse'),
        ('AVENUE', 'Yakata'),
        ('AVENUE', 'Yoko'),
        ('AVENUE', 'Yolo'),
        ('RUE', 'Babira'),
        ('RUE', 'Baboro'),
        ('RUE', 'Bagata'),
        ('RUE', 'Baleke'),
        ('RUE', 'Balinga'),
        ('RUE', 'Bamanga'),
        ('RUE', 'Bambili'),
        ('RUE', 'Baneba'),
        ('RUE', 'Bangba'),
        ('RUE', 'Barumbi'),
        ('RUE', 'Bemeli'),
        ('RUE', 'Benkana'),
        ('RUE', 'Biamange'),
        ('RUE', 'Bokuma'),
        ('RUE', 'Bolafa'),
        ('RUE', 'Boleko'),
        ('RUE', 'Bolia'),
        ('RUE', 'Bolobo'),
        ('RUE', 'Bomenge'),
        ('RUE', 'Bondo'),
        ('RUE', 'Bosenge'),
        ('RUE', 'Bosoku'),
        ('RUE', 'Bosso'),
        ('RUE', 'Bukavu'),
        ('RUE', 'Buma'),
        ('RUE', 'de Boyera'),
        ('RUE', 'de Bozene'),
        ('RUE', 'de Elipa'),
        ('RUE', 'de Kanda-Kanda'),
        ('RUE', 'de Moanda'),
        ('RUE', 'de Tshikapa'),
        ('RUE', 'Dembo'),
        ('RUE', 'Denis'),
        ('RUE', 'Dibaya'),
        ('RUE', 'Duaru'),
        ('RUE', 'Eala'),
        ('RUE', 'Elengesa'),
        ('RUE', 'Gama'),
        ('RUE', 'Gombari'),
        ('RUE', 'Ikelemba'),
        ('RUE', 'Ingende'),
        ('RUE', 'Inzia'),
        ('RUE', 'Isangila'),
        ('RUE', 'Kalu'),
        ('RUE', 'Kamina'),
        ('RUE', 'Kanda-Kanda'),
        ('RUE', 'Kasangulu'),
        ('RUE', 'Katu'),
        ('RUE', 'kimpwanza'),
        ('RUE', 'Kingabwa'),
        ('RUE', 'Kingete'),
        ('RUE', 'Kingoyo'),
        ('RUE', 'Kinzuzi'),
        ('RUE', 'Kombe'),
        ('RUE', 'Kwilu'),
        ('RUE', 'Lindja'),
        ('RUE', 'Lodja'),
        ('RUE', 'Lokolenge'),
        ('RUE', 'Londo'),
        ('RUE', 'Lopori'),
        ('RUE', 'Lubaya'),
        ('RUE', 'Lukenie'),
        ('RUE', 'Lukutu'),
        ('RUE', 'Lutunu'),
        ('RUE', 'Mabinza'),
        ('RUE', 'Makanza'),
        ('RUE', 'Mangai'),
        ('RUE', 'Masi-Manimba'),
        ('RUE', 'Matete'),
        ('RUE', 'Mayidi'),
        ('RUE', 'Mokaria'),
        ('RUE', 'Mompono'),
        ('RUE', 'Monkoto'),
        ('RUE', 'Mosango'),
        ('RUE', 'Movenda'),
        ('RUE', 'Mpozo'),
        ('RUE', 'Ndingba'),
        ('RUE', 'Ndjombo'),
        ('RUE', 'Niangara'),
        ('RUE', 'Niemba'),
        ('RUE', 'Nioki'),
        ('RUE', 'Oshwe'),
        ('RUE', 'Panga'),
        ('RUE', 'Popo Kabaka'),
        ('RUE', 'Sakania'),
        ('RUE', 'Semendwa'),
        ('RUE', 'Simba'),
        ('RUE', 'Toyokana'),
        ('RUE', 'Tshikapa'),
        ('RUE', 'Tumbumani'),
        ('RUE', 'Turumbu'),
        ('RUE', 'Vista'),
        ('RUE', 'Wafania'),
        ('RUE', 'Wagenia'),
        ('RUE', 'Wahanga'),
        ('RUE', 'Watsa'),
        ('RUE', 'Yakata'),
        ('RUE', 'Yalingo'),
        ('RUE', 'Yangambi'),
        ('RUE', 'Yanonge'),
        ('RUE', 'Yolo'),
        ('RUE', 'Zoao'),
    ],
    'Kasa-Vubu': [
        ('AVENUE', '1ère Rue'),
        ('AVENUE', 'Assolongo'),
        ('AVENUE', 'Assossa'),
        ('AVENUE', 'Birmanie'),
        ('AVENUE', 'Bungu'),
        ('AVENUE', 'Busu-Djanoa'),
        ('AVENUE', 'de la Force Publique'),
        ('AVENUE', 'de la Libération'),
        ('AVENUE', 'de la République'),
        ('AVENUE', 'de la Victoire'),
        ('AVENUE', 'de Zomfi'),
        ('AVENUE', 'des Huileries'),
        ('AVENUE', 'des Sports'),
        ('AVENUE', 'Dialele'),
        ('AVENUE', 'Enseignement'),
        ('AVENUE', 'Gambela'),
        ('AVENUE', 'Henri Bongolo'),
        ('AVENUE', 'Kasa-Vubu'),
        ('AVENUE', 'Lisala'),
        ('AVENUE', 'Lokalama'),
        ('AVENUE', 'Lukandu'),
        ('AVENUE', 'Luozi'),
        ('AVENUE', 'Maringa'),
        ('AVENUE', 'Mosambo'),
        ('AVENUE', 'Mpozo'),
        ('AVENUE', 'Opala'),
        ('AVENUE', 'Palais du Peuple'),
        ('AVENUE', 'Place du 17 Mai'),
        ('AVENUE', 'Rond-point Kimpwanza'),
        ('AVENUE', 'Rond-point Moulaert'),
        ('AVENUE', 'Saio'),
        ('AVENUE', 'Sendwe'),
        ('AVENUE', 'Shaba'),
        ('AVENUE', 'Sumbi'),
        ('AVENUE', 'Triomphal'),
        ('RUE', 'Assossa'),
        ('RUE', 'Banalia'),
        ('RUE', 'Befale'),
        ('RUE', 'Bomboma'),
        ('RUE', 'Bongandanga'),
        ('RUE', 'Bosobolo'),
        ('RUE', 'Busu-Melo'),
        ('RUE', 'de Binanga'),
        ('RUE', 'de Bombo'),
        ('RUE', 'de Dembo'),
        ('RUE', 'de Kanda-kanda'),
        ('RUE', 'de Kasangulu'),
        ('RUE', 'de Kibambi'),
        ('RUE', 'de Kiduma'),
        ('RUE', 'de Kimbola'),
        ('RUE', 'de Kimpemba'),
        ('RUE', 'de KImwenza'),
        ('RUE', 'de Kimwisi'),
        ('RUE', 'de Kinanga'),
        ('RUE', 'de Kindongolosi'),
        ('RUE', 'de Kintanu'),
        ('RUE', 'de Kinzwana'),
        ('RUE', 'de Kipaku'),
        ('RUE', 'de Kipaku bis'),
        ('RUE', 'de Kivuka'),
        ('RUE', 'de Lemfu'),
        ('RUE', 'de Mbonda'),
        ('RUE', 'de Selo'),
        ('RUE', 'de Yongo'),
        ('RUE', 'Dibaya'),
        ('RUE', 'Djolu'),
        ('RUE', 'Eala'),
        ('RUE', 'Faradje'),
        ('RUE', 'Gemena'),
        ('RUE', 'Ikelemba'),
        ('RUE', 'Inzia'),
        ('RUE', 'Irebu'),
        ('RUE', 'Kanda-Kanda'),
        ('RUE', 'Kansavu'),
        ('RUE', 'Khartoum'),
        ('RUE', 'Loango'),
        ('RUE', 'Lodja'),
        ('RUE', 'Lopori'),
        ('RUE', 'Lukula'),
        ('RUE', 'Mangai'),
        ('RUE', 'Masi-Manimba'),
        ('RUE', 'Momboyo'),
        ('RUE', 'Oshwe'),
        ('RUE', 'Popo Kabaka'),
        ('RUE', 'Sandoa'),
        ('RUE', 'Sundi'),
        ('RUE', 'Tsanga'),
        ('RUE', 'Tshikapa'),
        ('RUE', 'Tuidi'),
        ('RUE', 'Yahuma'),
        ('RUE', 'Yakata'),
    ],
    'Kintambo': [
        ('AVENUE', 'Afrique'),
        ('AVENUE', 'Basoko'),
        ('AVENUE', 'Benseke'),
        ('AVENUE', 'Bobobliko'),
        ('AVENUE', 'Bompete'),
        ('AVENUE', 'Canetton'),
        ('AVENUE', 'Chrétienne'),
        ('AVENUE', 'Chute de Lofoy'),
        ('AVENUE', 'Cocotier'),
        ('AVENUE', 'de Bangala'),
        ('AVENUE', 'de l’Hôpital'),
        ('AVENUE', 'de l’OUA'),
        ('AVENUE', 'de la Santé'),
        ('AVENUE', 'de la Source'),
        ('AVENUE', 'de Madimba'),
        ('AVENUE', 'de Tabora'),
        ('AVENUE', 'du Grand Séminaire'),
        ('AVENUE', 'Eben Ezer'),
        ('AVENUE', 'Joli-Parc'),
        ('AVENUE', 'Kasa-Vubu'),
        ('AVENUE', 'Kindu'),
        ('AVENUE', 'Kisangani'),
        ('AVENUE', 'Kivu'),
        ('AVENUE', 'Komoriko'),
        ('AVENUE', 'Kwango'),
        ('AVENUE', 'La Paix'),
        ('AVENUE', 'Lado'),
        ('AVENUE', 'Liberté'),
        ('AVENUE', 'Limaya'),
        ('AVENUE', 'Lubudi'),
        ('AVENUE', 'Lukengo'),
        ('AVENUE', 'Lumière'),
        ('AVENUE', 'madimba'),
        ('AVENUE', 'Maniema'),
        ('AVENUE', 'Ngaliema'),
        ('AVENUE', 'Pont Makelele'),
        ('AVENUE', 'Rufidji'),
        ('AVENUE', 'Tanganika'),
        ('AVENUE', 'Terrain'),
        ('AVENUE', 'Tshibambi'),
        ('AVENUE', 'Uele'),
        ('RUE', 'Abbé Kaozi'),
        ('RUE', 'Bakusu'),
        ('RUE', 'Banana'),
        ('RUE', 'Bassin Vert'),
        ('RUE', 'Boma'),
        ('RUE', "d'Inongo"),
        ('RUE', 'de Bandundu'),
        ('RUE', 'de Budjala'),
        ('RUE', 'de Dima'),
        ('RUE', "de L'équateur"),
        ('RUE', 'de Lomami'),
        ('RUE', 'de Lusambo'),
        ('RUE', 'de Mahenge'),
        ('RUE', 'de Mai Ndombe'),
        ('RUE', 'de Matadi'),
        ('RUE', 'de Vivi'),
        ('RUE', 'des Aigles'),
        ('RUE', 'des Eperviers'),
        ('RUE', 'des Hirondelles'),
        ('RUE', 'des Moineaux'),
        ('RUE', 'des Rosiers'),
        ('RUE', 'des Vautours'),
        ('RUE', 'du Kasai'),
        ('RUE', 'Frère Mboyo'),
        ('RUE', 'Idiofa'),
        ('RUE', 'Ituri'),
        ('RUE', 'Kasanga'),
        ('RUE', 'Kimbala'),
        ('RUE', 'Kimbao'),
        ('RUE', 'Kimbele'),
        ('RUE', 'Kimbwala'),
        ('RUE', 'Kimona'),
        ('RUE', 'Kimvula'),
        ('RUE', 'Kinsuka'),
        ('RUE', 'Kitona'),
        ('RUE', 'Kobo'),
        ('RUE', 'Kokolo'),
        ('RUE', 'Kwamouth'),
        ('RUE', 'Kwilu'),
        ('RUE', 'Lisasi'),
        ('RUE', 'Loadi'),
        ('RUE', 'Lunionzo'),
        ('RUE', 'Lutendele'),
        ('RUE', 'Mosamba'),
        ('RUE', 'Mungamba'),
        ('RUE', 'Ngaliema'),
        ('RUE', 'Sangra'),
        ('RUE', 'Sankuru'),
        ('RUE', 'Seke Banza'),
        ('RUE', 'Tulipiers'),
        ('RUE', 'Ubangi'),
        ('RUE', 'Utexco'),
        ('RUE', 'Wamba'),
    ],
}

def avenues_for_commune(commune: str) -> list[tuple[str, str]]:
    """Voies OSM pour une commune Kinshasa."""
    exact = KINSHASA_AVENUES_BY_COMMUNE.get(commune)
    if exact:
        return list(exact)
    return list(KINSHASA_CITY_AVENUES)

