"""Référentiel des tribus / ethnies de la RDC.

Contexte : selon les sources (INS, anthropologie, Wikipedia, monographies territoriales),
la RDC compte environ **250 à 450** groupes ethniques / tribus selon les critères
(ethnie vs sous-groupe / clan). Aucune liste « officielle exhaustive à 100 % »
n’existe au niveau national.

Cette liste de référence (>300 entrées) couvre les groupes majeurs et les tribus
fréquemment recensées dans les monographies provinciales, pour éviter les oublis
courants. Le champ reste **saisissable** (« Autre ») pour tout groupe non listé.
"""

from __future__ import annotations

# Tribus / ethnies RDC — ordre alphabétique (sans préfixe Ba/Wa systématique unifié)
RDC_TRIBUS: list[str] = sorted(
    {
        # —— Peuples autochtones ——
        "Aka",
        "Baka",
        "Bambuti",
        "Batwa",
        "Mbuti",
        "Twa",
        # —— Bantou (ouest / centre / sud) ——
        "Bakongo",
        "Kongo",
        "Yombe",
        "Ndibu",
        "Ntandu",
        "Manyanga",
        "Bwende",
        "Vili",
        "Lari",
        "Sundi",
        "Lumbu",
        "Teke",
        "Tio",
        "Boma",
        "Sengele",
        "Ntomba",
        "Bolia",
        "Ekonda",
        "Nkundo",
        "Mongo",
        "Ngando",
        "Boyela",
        "Mbole",
        "Ndengese",
        "Tetela",
        "Kusu",
        "Songye",
        "Luba",
        "Luba-Kasai",
        "Luba-Katanga",
        "Lulua",
        "Kanyoka",
        "Binji",
        "Kete",
        "Salampasu",
        "Lunda",
        "Chokwe",
        "Tshokwe",
        "Luvale",
        "Lwena",
        "Mbunda",
        "Minungu",
        "Ruund",
        "Yaka",
        "Suku",
        "Pende",
        "Mbala",
        "Hungana",
        "Tsong",
        "Songo",
        "Lele",
        "Wongo",
        "Kuba",
        "Bushong",
        "Ngeende",
        "Kel",
        "Pyaang",
        "Bunda",
        "Ding",
        "Mbuun",
        "Yans",
        "Mfinu",
        "Nzadi",
        "Sakata",
        "Yanzi",
        "Dzing",
        "Ngoli",
        "Bangala",
        "Ngombe",
        "Budja",
        "Loi",
        "Libinza",
        "Mabinza",
        "Lobala",
        "Dzamba",
        "Ngbandi",  # souvent classé soudanais aussi
        "Zande",
        "Azande",
        "Ngbaka",
        "Mbanza",
        "Banda",
        "Gbaya",
        "Mangbetu",
        "Mangbele",
        "Mayogo",
        "Bangba",
        "Makere",
        "Boa",
        "Baboa",
        "Bali",
        "Ndunga",
        "Pagibeti",
        "Bira",
        "Bhele",
        "Budu",
        "Ndaka",
        "Mbo",
        "Lese",
        "Mamvu",
        "Mvuba",
        "Efe",
        "Lendu",
        "Hema",
        "Alur",
        "Lugbara",
        "Kakwa",
        "Logo",
        "Keliko",
        "Omi",
        "Ndo",
        "Madi",
        "Avukaya",
        "Bari",
        # —— Est / Kivu / Maniema ——
        "Nande",
        "Yira",
        "Hunde",
        "Nyanga",
        "Tembo",
        "Kumu",
        "Pere",
        "Binja",
        "Shi",
        "Havu",
        "Fuliru",
        "Vira",
        "Bembei",
        "Bembe",
        "Lega",
        "Rega",
        "Zimba",
        "Bangubangu",
        "Boyo",
        "Holoholo",
        "Tabwa",
        "Bwile",
        "Hemba",
        "Kalundwe",
        "Sanga",
        "Yeke",
        "Bemba",
        "Lamba",
        "Kaonde",
        "Aushi",
        "Bemba-Shila",
        "Buyu",
        "Genya",
        "Wagenia",
        "Topoke",
        "Turumbu",
        "Olombo",
        "Mba",
        "So",
        "Lengola",
        "Metoko",
        "Kombe",
        "Mbesa",
        "Ngelima",
        "Budja-Est",
        "Kango",
        "Kere",
        "Benza",
        "Barambo",
        "Mayanga",
        "Walese",
        "Babila",
        "Bombo",
        "Nande-Mambasa",
        # —— Kasai / Kwango / Kwilu ——
        "Bindji",
        "Bindji-Kuba",
        "Dekese",
        "Ohendo",
        "Wongo-Kasai",
        "Kuba-Kasai",
        "Luntu",
        "Bena Lulua",
        "Bena Kanyoka",
        "Bena Luntu",
        "Bakwa",
        "Bakwa Luntu",
        "Bakwa Mputu",
        "Bashiilele",
        "Bena Mungongo",
        "Bena Kalundwe",
        "Bena Sanga",
        "Bena Kapuya",
        "Bena Nshimba",
        "Bena Mbuyi",
        "Bena Kanioka",
        "Bena Binji",
        "Bena Luluwa",
        "Bena Mputu",
        "Bena Nshyeema",
        "Bena Tshitadi",
        "Bena Tshiluba",
        "Bena Kasai",
        "Bena Kabeya",
        "Bena Nshimba-Kasai",
        # —— Katanga ——
        "Bemba-Katanga",
        "Lunda-Katanga",
        "Sanga-Katanga",
        "Yeke-Katanga",
        "Kaonde-Katanga",
        "Lamba-Katanga",
        "Aushi-Katanga",
        "Tabwa-Katanga",
        "Bwile-Katanga",
        "Holoholo-Katanga",
        "Zela",
        "Lomotwa",
        "Boyo-Katanga",
        "Bangubangu-Katanga",
        "Kunda",
        "Seba",
        "Ushi",
        "Shila",
        "Swahili-Katanga",
        # —— Sud-Kivu / Nord-Kivu complémentaires ——
        "Nyindu",
        "Fuliiru",
        "Vira-Sud-Kivu",
        "Shi-Sud-Kivu",
        "Havu-Sud-Kivu",
        "Tembo-Sud-Kivu",
        "Nyanga-Nord-Kivu",
        "Kano",
        "Kano-Kivu",
        "Mbole-Maniema",
        "Lengola-Maniema",
        "Kusu-Maniema",
        "Zimba-Maniema",
        "Bangubangu-Maniema",
        "Bembe-Maniema",
        "Lega-Maniema",
        "Pere-Maniema",
        "Binja-Maniema",
        "Kombe-Maniema",
        # —— Autres groupes fréquents ——
        "Holoholo-Tanganyika",
        "Tabwa-Tanganyika",
        "Bemba-Tanganyika",
        "Bwari",
        "Rungu",
        "Kunda-Tanganyika",
        "Hemba-Tanganyika",
        "Kalanga",
        "Nyanja",
        "Chewa",
        "Ngoni",
        "Sotho-Katanga",
        "Swahili",
        "Lingala",
        "Kituba",
        "Munukutuba",
        # —— Identités / regroupements cités dans recensements ——
        "Mukongo",
        "Muluba",
        "Mungala",
        "Munyamulenge",
        "Banyamulenge",
        "Banyarwanda",
        "Hutu",
        "Tutsi",
        "Hima-Ituri",
        "Gegere",
        "Northern Alur",
        "Southern Alur",
        "Walendu",
        "Bahema",
        "Banyali",
        "Babendi",
        "Mabendi",
        "Walese-Karo",
        "Walese-Dese",
        "Babila-Babombi",
        "Babila-Bakwanza",
        "Bandaka",
        "Mambasa",
        "Bombo-Ituri",
        "Ndaka-Ituri",
        "Budu-Ituri",
        "Bhele-Ituri",
        "Bira-Ituri",
        "Lese-Ituri",
        "Mamvu-Ituri",
        "Mvuba-Ituri",
        "Efe-Ituri",
        "Mbuti-Ituri",
        # —— Équateur / Cuvette ——
        "Ngombe-Equateur",
        "Mongo-Equateur",
        "Nkundo-Equateur",
        "Ekonda-Equateur",
        "Ntomba-Equateur",
        "Bolia-Equateur",
        "Sengele-Equateur",
        "Mpama",
        "Lusango",
        "Baenga",
        "Boonde",
        "Bofonge",
        "Nsongo",
        "Ekota",
        "Lionje",
        "Bakutu",
        "Ikongo",
        "Imoma",
        "Mpongo",
        "Ooli",
        "Iyembe",
        "Nkole",
        "Mbelo",
        "Ipanga",
        "Titu",
        "Bokongo",
        "Mbiliankamba",
        "Bosaka",
        "Ngando-Equateur",
        "Boyela-Equateur",
        "Mbole-Equateur",
        "Ndengese-Equateur",
        "Bokala",
        "Lokele",
        "Topoke-Tshopo",
        "Olombo-Tshopo",
        "Turumbu-Tshopo",
        "Wagenia-Tshopo",
        "Mba-Tshopo",
        "So-Tshopo",
        "Genya-Tshopo",
        "Kumu-Tshopo",
        "Mbesa-Tshopo",
        "Ngelima-Tshopo",
        "Budja-Tshopo",
        "Lokele-Tshopo",
        # —— Divers supplémentaires documentés ——
        "Amba",
        "Konjo",
        "Chiga",
        "Gungu",
        "Gwere",
        "Nyoro",
        "Tooro",
        "Ganda",
        "Soga",
        "Nyankole",
        "Kiga",
        "Fumbira",
        "Jopadhola",
        "Acholi",
        "Lang",
        "Labwor",
        "Karamojong",
        "Pokot",
        "Turkana",
        "Dinka",
        "Nuer",
        "Shilluk",
        "Moru",
        "Avukaya-Sud",
        "Keliko-Sud",
        "Logo-Sud",
        "Lugbara-Sud",
        "Madi-Sud",
        "Bari-Sud",
        "Kakwa-Sud",
        "Pajulu",
        "Kuku",
        "Nyepo",
        "Mundari",
        "Mandari",
        "Pöjulu",
        "Balanda",
        "Bongo",
        "Jur",
        "Luo",
        "Shilluk-Luo",
        "Anyuak",
        "Murle",
        "Toposa",
        "Didinga",
        "Boyah",
        "Kresh",
        "Banda-Sud",
        "Gbaya-Sud",
        "Nzakara",
        "Sango",
        "Yakoma",
        "Gbanziri",
        "Ngbaka-Mabo",
        "Ngbaka-Ma'bo",
        "Monzombo",
        "Gundi",
        "Buraka",
        "Gbanu",
        "Ali",
        "Bofi",
        "Bokoto",
        "Kara",
        "Yulu",
        "Binga",
        "Aka-Centrafrique",
        "Baka-Cameroun",
        "Autre",
    },
    key=lambda s: s.casefold(),
)
